apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: snapshot-controller
    namespace: kube-system
    repo: oci://ghcr.io/piraeusdatastore/helm-charts/
    name: snapshot-controller
    version: 4.1.0
