---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/traefik.io/middleware-v1alpha1.json

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2
  namespace: application
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  forwardAuth:
    address: http://oauth2proxy.application.svc.cluster.local:4180/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
