---
# https://github.com/envoyproxy/gateway/blob/main/charts/gateway-addons-helm/values.yaml
prometheus:
  enabled: false
grafana:
  enabled: false
fluent-bit:
  enabled: false
alloy:
  enabled: false
loki:
  enabled: false
tempo:
  enabled: false
opentelemetry-collector:
  enabled: false
