---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/openebs.io/diskpool-v1beta3.json
apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: fast-1-1
  namespace: openebs
spec:
  node: worker-1
  disks: ["aio:///dev/disk/by-path/pci-0000:01:02.0-scsi-0:0:0:1"]
  topology:
    labelled:
      tier: fast
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/openebs.io/diskpool-v1beta3.json
apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: fast-2-1
  namespace: openebs
spec:
  node: worker-2
  disks: ["aio:///dev/disk/by-path/pci-0000:01:02.0-scsi-0:0:0:1"]
  topology:
    labelled:
      tier: fast
