---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: prometheus-operator-crds
    repo: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    releaseName: prometheus-operator-crds
    version: 22.0.0
    valuesFile: values.yaml
