# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/external-secrets.io/externalsecret-v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-pve-exporter-creds
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  refreshPolicy: Periodic
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: prometheus-pve-exporter/app
