---
resources:
  requests:
    cpu: 50m
    memory: 32Mi

prometheus:
  service:
    enabled: true
  monitor:
    enabled: true

replicaCount: 2

service:
  clusterIP: 10.43.0.10

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            k8s-app: coredns
            app.kubernetes.io/name: coredns
        topologyKey: kubernetes.io/hostname
        matchLabelKeys:
          - pod-template-hash
