---
name: lbh-lab

path: ~/Workspace/moonlight8978/lbh-lab

windows:
  - name: code
    panes:
      - name: Editor
        flex: 100
        commands:
          - command: $EDITOR
        focus: true
      - flex: 37
