---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.5
    hooks:
      - id: terraform_fmt
        files: ^(.*\.(tf|tfvars|hcl))$
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.0
    hooks:
      - id: yamlfmt
        exclude: ^.woodpecker/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.43.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]
