---
# yaml-language-server: $schema=https://raw.githubusercontent.com/google/yamlfmt/refs/heads/main/schema.json

formatter:
  type: basic
  include_document_start: true
  retain_line_breaks_single: true
  disallow_anchors: false
  disable_alias_key_correction: true
