---
version: "3"

tasks:
  tf:stack:
    vars: &tf_vars
      workdir: "{{index .CLI_ARGS_LIST 0}}"
      args: '{{slice .CLI_ARGS_LIST 1 | join " "}}'
    dir: "{{.workdir}}"
    cmd: terragrunt stack {{ternary "" "run" (hasPrefix "output" .args)}} {{.args}} --non-interactive --auth-provider-cmd "sops decrypt {{.ROOT_DIR}}/secrets.yml --output-type json"

  tf:unit:
    vars: *tf_vars
    dir: "{{.workdir}}"
    cmd: terragrunt {{.args}} --auth-provider-cmd "sops decrypt {{.ROOT_DIR}}/secrets.yml --output-type json" --all --non-interactive

  sops:dec:
    cmds:
      - sops decrypt secrets.yml > secrets.dec.yml

  sops:enc:
    cmds:
      - sops encrypt secrets.dec.yml > secrets.yml

  talos:secrets:
    cmds:
      - task: sops:dec
      - talosctl gen secrets -o talos-secrets.dec.yml --force
      - |
        cat talos-secrets.dec.yml | yq eval '{ "talos": . }' > /tmp/talos-secrets.dec.yml
      - defer: rm -rf /tmp/secrets.yml /tmp/talos-secrets.yml
      - |
        yq eval-all '. as $item ireduce ({}; . * $item )' /tmp/talos-secrets.yml /tmp/secrets.yml | sops encrypt --input-type yaml --output-type yaml --filename-override secrets.dec.yml > secrets.yml

  talos:config:
    dir: "kubernetes/talos"
    cmds:
      - sops decrypt {{.ROOT_DIR}}/secrets.yml | yq -r '.talos' | talosctl gen config --with-secrets /dev/stdin lbhlab https://10.242.20.160:6443 --config-patch @patch.yaml {{.CLI_ARGS}}
      - talosctl --talosconfig=./talosconfig config endpoints 10.242.20.161

  talos:reset:
    vars:
      IP: "{{ index .CLI_ARGS_LIST 0 }}"
    dir: kubernetes/talos
    cmd: talosctl reset --nodes {{.IP}} --talosconfig talosconfig

  # controlplane or worker
  talos:apply:*:
    vars:
      ROLE: "{{ index .MATCH 0 }}"
      MACHINE: "{{ index .CLI_ARGS_LIST 0 }}"
      IP: "{{ index .CLI_ARGS_LIST 1 }}"
      ARGS: '{{slice .CLI_ARGS_LIST 2 | join " "}}'
    dir: kubernetes/talos
    cmds:
      - talosctl machineconfig patch {{.ROLE}}.yaml -p @patch.yaml -p @nodes/{{.MACHINE}}.yaml | talosctl apply-config --file /dev/stdin --nodes {{.IP}} {{.ARGS}}

  talos:reboot:
    vars:
      IP: "{{ index .CLI_ARGS_LIST 0 }}"
    dir: kubernetes/talos
    cmds:
      - talosctl reboot --nodes {{.IP}} --talosconfig talosconfig

  talos:boostrap:
    dir: kubernetes/talos
    cmds:
      - task: talos:apply:controlplane
        vars:
          ROLE: controlplane
          MACHINE: control-1
          IP: 10.242.20.161
          ARGS: --insecure
      - task: talos:apply:controlplane
        vars:
          ROLE: controlplane
          MACHINE: control-2
          IP: 10.242.20.162
          ARGS: --insecure
      - task: talos:apply:controlplane
        vars:
          ROLE: controlplane
          MACHINE: control-3
          IP: 10.242.20.163
          ARGS: --insecure
      - task: talos:apply:worker
        vars:
          ROLE: worker
          MACHINE: worker-1
          IP: 10.242.20.171
          ARGS: --insecure
      - task: talos:apply:worker
        vars:
          ROLE: worker
          MACHINE: worker-2
          IP: 10.242.20.172
          ARGS: --insecure
      - talosctl bootstrap --talosconfig talosconfig --nodes 10.242.20.161
      - talosctl kubeconfig --talosconfig talosconfig --nodes 10.242.20.161
      - yq -i '.clusters[0].cluster.server = "https://10.242.20.161:6443"' kubeconfig

  k8s:nodelabel:
    env:
      KUBECONFIG: "{{.ROOT_DIR}}/kubernetes/talos/kubeconfig"
    cmds:
      - for: [worker-1, worker-2]
        cmd: kubectl label node {{.ITEM}} node-role.kubernetes.io/worker=worker
      - for: [worker-1, worker-2]
        cmd: kubectl label node {{.ITEM}} node-role.kubernetes.io/openebs=openebs

  k8s:bootstrap:
    dir: kubernetes/charts
    cmds:
      - helmfile apply --skip-diff-on-install --suppress-diff
    env:
      KUBECONFIG: "{{.ROOT_DIR}}/kubernetes/talos/kubeconfig"

  argocd:login:
    env:
      KUBECONFIG: "{{.ROOT_DIR}}/kubernetes/talos/kubeconfig"
    cmds:
      - |
        PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d)
        argocd login 10.242.20.181 --username admin --password $PASSWORD --insecure

  argocd:bootstrap:
    cmds:
      - argocd app sync --project system

  bootstrap:
    cmds:
      - task: tf:unit
        vars:
          workdir: prod/kubernetes
          args: apply
      - task: talos:bootstrap
      - task: k8s:nodelabel
      - task: k8s:bootstrap
