---
version: "3"

includes:
  k8s: .taskfiles/k8s/Taskfile.yml
  pve: .taskfiles/pve/Taskfile.yml
  sops: .taskfiles/sops/Taskfile.yml
  vault: .taskfiles/vault/Taskfile.yml
  pki: .taskfiles/pki/Taskfile.yml

tasks:
  setup:
    cmds:
      - task: pve:setup
      - task: pve:debian # Need manual installation of Debian template

  k8s:
    cmds:
      - task: k8s:provision
      - task: k8s:bootstrap-apps
        # These vault tasks are already included in the helmfile sync hook
        # - task: vault:init
        # - task: vault:provision

  ca:
    cmds:
      - task: pki:ca
      - task: pki:inter
