---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: code-server
    namespace: application
    repo: oci://ghcr.io/bjw-s-labs/helm
    name: app-template
    version: 4.4.0
    valuesFile: values.yaml

resources:
  - manifests/externalsecret.yaml
