# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: traefik-internal
    namespace: kube-system
    repo: oci://ghcr.io/traefik/helm/
    name: traefik
    version: 37.1.1
    valuesFile: values.yaml

resources:
  - manifests/certificate.yaml
