---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json
# https://github.com/karakeep-app/helm-charts/blob/main/charts/karakeep/values.yaml
applicationHost: &hostname karakeep-10-242-20-170.lab-local.bichls.dev
applicationProtocol: https

controllers:
  karakeep:
    containers:
      karakeep:
        envFrom:
          - secret: karakeep-env
          - configMap: main
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 1Gi
  chrome:
    containers:
      chrome:
        args:
          - --no-sandbox
          - --disable-gpu
          - --remote-debugging-address=0.0.0.0
          - --remote-debugging-port=9222
          - --hide-scrollbars
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            memory: 1Gi
        securityContext:
          capabilities: null

secrets:
  karakeep:
    enabled: false
    stringData: {}
  meilesearch:
    enabled: false
    stringData: {}

configMaps:
  main:
    data:
      DISABLE_SIGNUPS: "true"
      NODE_ENV: production
      OPENAI_BASE_URL: https://generativelanguage.googleapis.com/v1beta/openai/
      INFERENCE_TEXT_MODEL: gemini-2.0-flash
      INFERENCE_IMAGE_MODEL: gemini-2.0-flash
      EMBEDDING_TEXT_MODEL: text-embedding-3-small
      INFERENCE_LANG: english

ingress:
  karakeep:
    enabled: false

route:
  main:
    parentRefs:
      - name: envoy
        namespace: envoy-gateway-system
    hostnames:
      - *hostname
    rules:
      - backendRefs:
          - name: karakeep
            port: 3000

# https://github.com/meilisearch/meilisearch-kubernetes/blob/main/charts/meilisearch/values.yaml
meilisearch:
  environment:
    MEILI_ENV: production
  auth:
    existingMasterKeySecret: karakeep-meilisearch-creds
  persistence:
    enabled: true
    storageClass: openebs-mayastor
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi
  serviceMonitor:
    enabled: true
