---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cicd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: CICD Components
  sourceRepos:
    - https://github.com/moonlight8978/lbh-lab.git
  destinations:
    - namespace: argocd
      name: in-cluster
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  syncWindows:
    - kind: allow
      schedule: "0 5 * * *"
      timeZone: "Asia/Bangkok"
      applications:
        - "*"
      duration: 1h
      manualSync: false
    - kind: deny
      schedule: "0 0-4,6-23 * * *"
      timeZone: "Asia/Bangkok"
      applications:
        - "*"
      duration: 1h
      manualSync: true
