apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - list:
        elements:
          - name: cilium
            project: system
            namespace: kube-system
          - name: cert-manager
            project: system
            namespace: cert-manager
  template:
    metadata:
      name: "{{.name}}"
    spec:
      project: "{{.project}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      source:
        repoURL: https://github.com/moonlight8978/lbh-lab.git
        targetRevision: main
        path: "charts/{{.path | default .name}}"
        kustomize: {}
      destination:
        name: in-cluster
        namespace: "{{.namespace}}"
