apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: argocd
spec:
  provider:
    vault:
      server: "http://my.vault.server:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kubernetes
          key: "token"
