---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/cert-manager.io/clusterissuer-v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    profile: classic
    privateKeySecretRef:
      name: letsencrypt-creds
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-creds
              key: api-token
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/cert-manager.io/clusterissuer-v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    profile: classic
    privateKeySecretRef:
      name: letsencrypt-staging-creds
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-creds
              key: api-token
