---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/cert-manager.io/clusterissuer-v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  selfSigned: {}
