apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - list:
        elements:
          - name: cilium
            namespace: kube-system
            project: system
            noServerSideDiff: true
            ignoreDifferences:
              - kind: Secret
                jsonPointers:
                  - /data/ca.crt
                  - /data/ca.key
                  - /data/tls.crt
                  - /data/tls.key
          - name: cert-manager
            namespace: cert-manager
            project: system
          - name: external-secrets
            namespace: external-secrets
            project: system
          - name: metallb
            namespace: metallb-system
            project: system
          - name: snapshot-controller
            namespace: kube-system
            project: system
          - name: rook-ceph
            namespace: rook-ceph
            project: system
          - name: traefik-internal
            namespace: kube-system
            project: system
            path: traefik/internal
          - name: prometheus
            namespace: monitoring
            project: system
          - name: vault
            namespace: vault
            project: system

          - name: argocd
            namespace: argocd
            project: cicd
          - name: argocd-apps
            namespace: argocd
            project: cicd
  template:
    metadata:
      name: "{{.name}}"
    spec:
      project: "{{.project}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ServerSideDiff=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
      source:
        repoURL: https://github.com/moonlight8978/lbh-lab.git
        targetRevision: main
        path: "charts/{{.path | default .name}}"
      destination:
        name: in-cluster
        namespace: "{{.namespace}}"
  templatePatch: |
    {{- with .noServerSideDiff }}
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=false
    {{- end }}

    spec:
      project: "{{.project}}"
      {{- with .ignoreDifferences }}
      ignoreDifferences:
        {{- range . }}
        -
          {{. | toYaml | nindent 6}}
        {{- end }}
      {{- end }}
