---
global:
  enabled: true
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 256Mi

injector:
  enabled: false

server:
  enabled: true

  standalone:
    enabled: false

  ha:
    enabled: true
    replicas: 2
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}

  logFormat: json

  resources:
    limits:
      memory: 4Gi
    requests:
      memory: 64Mi
      cpu: "50m"

  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"

  livenessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true"
    initialDelaySeconds: 60

  dataStorage:
    enabled: true
    storageClass: openebs-mayastor
    size: 500Mi

  auditStorage:
    enabled: true
    storageClass: openebs-mayastor
    size: 500Mi

  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: intermediate-ca
      cert-manager.io/common-name: &cn vault.10.242.20.150.sslip.io
      cert-manager.io/subject-organizations: LBH Lab
      cert-manager.io/subject-organizationalunits: Vault
      cert-manager.io/subject-countries: VN
      cert-manager.io/duration: 720h
      cert-manager.io/renew-before: 72h
    ingressClassName: traefik-internal
    hosts:
      - host: *cn
    tls:
      - secretName: vault.sslip.io
        hosts:
          - *cn

  # affinity: |
  #   podAntiAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchLabels:
  #           app.kubernetes.io/name: {{ template "vault.name" . }}
  #           app.kubernetes.io/instance: "{{ .Release.Name }}"
  #           component: server
  #       topologyKey: kubernetes.io/hostname

ui:
  enabled: true

serverTelemetry:
  serviceMonitor:
    enabled: true

  prometheusRules:
    enabled: true
    rules:
      - alert: vault-HighResponseTime
        annotations:
          message: The response time of Vault is over 1s on average over the last 5 minutes.
        expr: vault_core_handle_request{quantile="0.5", namespace="mynamespace"} > 1000
        for: 5m
        labels:
          severity: critical
