---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kyverno
    namespace: kyverno
    releaseName: kyverno
    repo: https://kyverno.github.io/kyverno/
    valuesFile: values.yaml

resources:
  - manifests/default-unreachable-toleration.yaml
