---
- name: Configure sysctl
  loop:
    - { name: fs.inotify.max_user_instances, value: "8192" }
    - { name: fs.inotify.max_user_watches, value: "524288" }
    - { name: net.ipv6.conf.all.disable_ipv6, value: "1" }
    - { name: net.ipv6.conf.default.disable_ipv6, value: "1" }
    - { name: net.ipv6.conf.lo.disable_ipv6, value: "1" }
    - { name: vm.nr_hugepages, value: "1024" }
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    reload: true
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf

- name: Configure Cloudflare CGNAT route
  ansible.builtin.copy:
    dest: /etc/netplan/99-cloudflare-cgnat.yaml
    owner: root
    group: root
    mode: "0600"
    content: |
      network:
        version: 2
        ethernets:
          {{ k8s_machine_eth_device }}:
            routes:
              - to: {{ cloudflare_cgnat_cidr }}
                via: {{ cloudflare_warp_connector_ip4 }}
              - to: 10.0.0.0/8
                via: 10.242.20.1

- name: Apply Cloudflare CGNAT route
  # ansible.builtin.shell: netplan apply
  loop:
    - "{{ cloudflare_cgnat_cidr }}"
  # Prevent cilium routes to be flushed when running `netplan apply`
  ansible.builtin.shell: |
    ip route add {{ item }} via {{ cloudflare_warp_connector_ip4 }}
