---
# https://github.com/external-secrets/bitwarden-sdk-server/blob/main/hack/cluster_issuer.yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/cert-manager.io/certificate-v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  secretName: bitwarden-tls-certs
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.local
    - external-secrets-bitwarden-sdk-server.external-secrets.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
    group: cert-manager.io
