---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com/api
      identityURL: https://vault.bitwarden.com/identity
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-creds
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc:9998
      caBundle:
      organizationID:
      projectID:
