---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/monitoring.coreos.com/servicemonitor-v1.json

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitea
  namespace: application
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - application
  selector:
    matchLabels:
      app.kubernetes.io/name: gitea
  endpoints:
    - port: http
      path: /metrics
      interval: 1m
