---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/external-secrets.io/externalsecret-v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-lapi-creds
  namespace: crowdsec-system
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  refreshPolicy: Periodic
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: crowdsec/lapi
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/external-secrets.io/externalsecret-v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-enroll-creds
  namespace: crowdsec-system
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  refreshPolicy: Periodic
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: crowdsec/enroll
