---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed
  namespace: cert-manager
spec:
  isCA: true
  commonName: LBH Lab Self-Signed CA
  secretName: self-signed
  privateKey:
    algorithm: RSA
    size: 4096
  duration: 87600h
  renewBefore: 720h
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: internal
spec:
  ca:
    secretName: self-signed
