---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json

defaultPodOptions:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
  annotations:
    reloader.stakater.com/auto: "true"

controllers:
  main:
    containers:
      main:
        image:
          repository: glanceapp/glance
          tag: v0.8.4
          pullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: &http 8080
        envFrom:
          - secret: glance-env
        probes:
          liveness:
            path: /api/healthz
            port: *http
          readiness:
            path: /api/healthz
            port: *http
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 256Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL

persistence:
  config:
    type: configMap
    name: glance-config
    globalMounts:
      - path: /app/config
  assets:
    type: configMap
    name: glance-assets
    globalMounts:
      - path: /app/assets

service:
  main:
    type: ClusterIP
    ports:
      http:
        port: *http
        targetPort: *http

route:
  main:
    hostnames:
      - glance-10-242-20-170.lab-local.bichls.dev
    parentRefs:
      - name: traefik-internal
        namespace: traefik-system
        sectionName: https
    rules:
      - backendRefs:
          - identifier: main
            port: *http
