apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: metallb
    namespace: metallb-system
    repo: oci://quay.io/metallb/chart/
    name: metallb
    version: 0.15.2
    valuesFile: values.yaml

resources:
  - manifests/ipaddresspool.yaml
  - manifests/l2advertisement.yaml
