---
speaker:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

controller:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi

prometheus:
  serviceAccount: prometheus
  namespace: metallb-system
  serviceMonitor:
    enabled: true
  prometheusRules:
    enabled: true
