---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/external-secrets.io/externalsecret-v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine-postgresql-creds
  namespace: application
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  refreshPolicy: Periodic
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: affine/pg
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/external-secrets.io/externalsecret-v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine-postgresql-root-creds
  namespace: application
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  refreshPolicy: Periodic
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: affine/pg-root
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/external-secrets.io/externalsecret-v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine-redis-creds
  namespace: application
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  refreshPolicy: Periodic
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: affine/redis
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/external-secrets.io/externalsecret-v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine-env
  namespace: application
  annotations:
    argocd.argoproj.io/sync-wave: "-1000"
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  refreshPolicy: Periodic
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: affine/app
