---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: gitea
    namespace: application
    repo: oci://ghcr.io/bjw-s-labs/helm
    name: app-template
    version: 4.4.0
    valuesFile: values.yaml

resources:
  - manifests/externalsecret.yaml
  - manifests/servicemonitor.yaml

configMapGenerator:
  - name: gitea-grafana-dashboards
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/gitea-overview.json
