---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json

defaultPodOptions:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
  annotations:
    reloader.stakater.com/auto: "true"

controllers:
  main:
    containers:
      main:
        image:
          repository: docker.gitea.com/gitea
          tag: 1.24.7-rootless
          pullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: &http 3000
          - name: ssh
            containerPort: &ssh 2222
        probes:
          liveness:
            path: /api/healthz
            port: *http
          readiness:
            path: /api/healthz
            port: *http
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        envFrom:
          - secret: gitea-env
          - configMap: main

configMaps:
  main:
    includeInChecksum: true
    data:
      GITEA_CUSTOM: /custom
      # https://docs.gitea.com/administration/config-cheat-sheet#use-environment-variables-to-setup-gitea
      GITEA__SECURITY__REVERSE_PROXY_AUTHENTICATION_USER: X-Auth-Request-User
      GITEA__SECURITY__REVERSE_PROXY_AUTHENTICATION_EMAIL: X-Auth-Request-Email
      GITEA__SECURITY__REVERSE_PROXY_AUTHENTICATION_FULL_NAME: X-Auth-Request-User
      GITEA__SECURITY__REVERSE_PROXY_TRUSTED_PROXIES: 10.42.0.0/16
      GITEA__SECURITY__INSTALL_LOCK: "false"
      GITEA__SERVICE__DISABLE_REGISTRATION: "true"

persistence:
  data:
    type: persistentVolumeClaim
    size: 2Gi
    accessMode: ReadWriteOnce
    storageClass: openebs-mayastor
    globalMounts:
      - path: /var/lib/gitea
  tmp:
    type: emptyDir
    sizeLimit: 100Mi
  config:
    type: emptyDir
    globalMounts:
      - path: /etc/gitea

service:
  main:
    type: ClusterIP
    ports:
      http:
        port: *http
        targetPort: *http
      ssh:
        port: *ssh
        targetPort: *ssh

route:
  main:
    hostnames:
      - gitea-10-242-20-170.lab-local.bichls.dev
    parentRefs:
      - name: traefik-internal
        namespace: traefik-system
        sectionName: https
    rules:
      - backendRefs:
          - identifier: main
            port: *http
        filters:
          - type: ExtensionRef
            extensionRef:
              group: traefik.io
              kind: Middleware
              name: oauth2
