---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: prometheus-operator-crds
    namespace: monitoring
    repo: oci://ghcr.io/prometheus-community/charts
    name: prometheus-operator-crds
    includeCRDs: true
    version: 24.0.1
