---
- name: Setup control plane nodes
  tags:
    - controller
  hosts: controller
  become: true
  roles:
    - ../roles/pkg-latest
    - ../roles/kubernetes/machine

- name: Setup worker nodes
  tags:
    - worker
  hosts: worker
  become: true
  roles:
    - ../roles/pkg-latest
    - ../roles/kubernetes/machine
    - ../roles/kubernetes/worker
