---
- name: Setup control plane nodes
  tags:
    - controller
  hosts: controller
  become: true
  pre_tasks:
    - include_tasks: ../tasks/load-secrets.yaml
    - set_fact:
        site_b_cidr: "{{ secrets.ansible_facts.site_b_cidr }}"
  roles:
    - ../roles/pkg-latest
    - ../roles/kubernetes/machine

- name: Setup worker nodes
  tags:
    - worker
  hosts: worker
  become: true
  pre_tasks:
    - include_tasks: ../tasks/load-secrets.yaml
    - set_fact:
        site_b_cidr: "{{ secrets.ansible_facts.site_b_cidr }}"
  roles:
    - ../roles/pkg-latest
    - ../roles/kubernetes/machine
    - ../roles/kubernetes/worker

- name: Setup NAS nodes
  tags:
    - nas
  hosts: nas
  become: true
  vars:
    nas_mount_point: /mnt/driver
    nas_device: /dev/disk/by-path/pci-0000:01:04.0-scsi-0:0:0:3-part2
  roles:
    - ../roles/kubernetes/nas
