# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  provision:
    cmds:
      - just terragrunt apply prod/kubernetes --all --non-interactive
    env:
      TF_VAR_kube_bootstrap: "true"

  bootstrap-apps:
    cmds:
      - ansible-playbook prod/kubernetes/playbooks/boostrap-apps.yaml
    env:
      KUBECONFIG: $HOME/.kube/lbhlab.yaml
