# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  provision:
    cmds:
      - just terragrunt apply prod/kubernetes --all --non-interactive
    env:
      TF_VAR_kube_bootstrap: "true"

  bootstrap-apps:
    dir: charts
    cmds:
      - until kubectl wait nodes --for=condition=Ready --all --timeout=10m; do sleep 5; done
      - helmfile apply --skip-diff-on-install --suppress-diff
    env:
      KUBECONFIG: $HOME/.kube/lbhlab.yaml
