---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  provision:
    cmds:
      - just terragrunt apply prod/kubernetes --all --non-interactive
    env:
      TF_VAR_kube_bootstrap: "true"

  bootstrap-apps:
    dir: charts
    cmds:
      - helmfile apply --skip-diff-on-install --suppress-diff
    env:
      KUBECONFIG: $HOME/.kube/lbhlab.yaml

  download-crt:
    env:
      KUBECONFIG: $HOME/.kube/lbhlab.yaml
    cmds:
      - kubectl get secret root-ca -n cert-manager -o jsonpath='{.data.tls\.crt}' | base64 -d > pki/internal/ca.crt
