---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/core/configmap-v1.json

apiVersion: v1
kind: ConfigMap
metadata:
  name: karakeep-kopia
  namespace: application
  labels:
    volsync/kopia: cloudflare
  annotations:
    volsync/kopia-repository: karakeep
    argocd.argoproj.io/sync-wave: "100"
data: {}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/volsync.backube/replicationsource-v1alpha1.json

apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: karakeep-db
  namespace: application
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  sourcePVC: data-karakeep-0
  trigger:
    schedule: "0 19 * * *"
  kopia:
    repository: karakeep-kopia-cloudflare
    copyMethod: Snapshot
    volumeSnapshotClassName: openebs-mayastor
    cacheStorageClassName: openebs-mayastor-single
    storageClassName: openebs-mayastor-backup
    policyConfig:
      configMapName: kopia-policy
      globalPolicyFilename: global_policy.json
    moverSecurityContext:
      fsGroup: 0
      runAsGroup: 0
      runAsUser: 0
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/volsync.backube/replicationdestination-v1alpha1.json

apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: karakeep-db
  namespace: application
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  trigger:
    manual: restore
  kopia:
    repository: karakeep-kopia-cloudflare
    copyMethod: Direct
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
    moverSecurityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsUser: 1000
    destinationPVC: data-karakeep-0
