---
- name: Add cloudflare gpg key
  ansible.builtin.shell: curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg

- name: Add cloudflare apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ {{ ansible_distribution_release }} main"
    state: present
    filename: cloudflare-client

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    state: latest
    pkg:
      - cloudflare-warp

- name: Configure sysctl
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    reload: true
    sysctl_file: /etc/sysctl.d/99-warp-svc.conf

- name: Register
  become: false
  ansible.builtin.shell: warp-cli --accept-tos connector new {{ cloudflare_warp_connector_token }}
  args:
    creates: /var/lib/cloudflare-warp/reg.json

- name: Connect to cloudflare
  become: false
  ansible.builtin.shell: warp-cli --accept-tos connect

# Fix https issue with cilium virtual IP
# Cilium add overhead for tls traffic
# So we need to clamp the mss to prevent it exceed the cloudflare mtu, which is 1280
- name: Check mss clamp rule
  ansible.builtin.shell: >-
    iptables -t mangle -C FORWARD -p tcp --tcp-flags SYN,RST SYN
    -j TCPMSS --set-mss 1240
  register: check_clamp_rule
  ignore_errors: true

- name: Insert TCPMSS clamp rule if not present
  ansible.builtin.shell: >
    iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN
    -j TCPMSS --set-mss 1240
  when: check_clamp_rule.rc != 0
