---
# https://github.com/argoproj/argo-helm/blob/main/charts/argocd-apps/values.yaml

x-data:
  repo: &repo https://github.com/moonlight8978/lbh-lab.git
  branch: &branch main
  cluster: &cluster in-cluster

applicationsets:
  prod:
    namespace: argocd
    finalizers: []
    #   - resources-finalizer.argocd.argoproj.io
    goTemplate: true
    goTemplateOptions: ["missingkey=default"]
    generators:
      - list:
          elements:
            - name: argocd-apps
              namespace: argocd
              project: argocd
            - name: argocd
              namespace: argocd
              project: argocd
              ignoreDifferences:
                - kind: Secret
                  name: argocd-secret
                  jsonPointers:
                    - /metadata/annotations/argocd.argoproj.io~1tracking-id

            - name: cilium
              namespace: kube-system
              project: core
              ignoreDifferences:
                - kind: Secret
                  name: cilium-ca
                  jsonPointers:
                    - /data/ca.crt
                    - /data/ca.key
                - kind: Secret
                  name: hubble-relay-client-certs
                  jsonPointers:
                    - /data/ca.crt
                    - /data/tls.crt
                    - /data/tls.key
                - kind: Secret
                  name: hubble-server-certs
                  jsonPointers:
                    - /data/ca.crt
                    - /data/tls.crt
                    - /data/tls.key
            - name: coredns
              namespace: kube-system
              project: core
            - name: cert-manager
              namespace: cert-manager
              project: core
            - name: external-secrets
              namespace: external-secrets
              project: core
            - name: addons
              namespace: kube-system
              project: core
            - name: openebs
              namespace: openebs
              project: core
              skipCrdsCheck: true
              ignoreDifferences:
                - kind: Secret
                  name: openebs-etcd-jwt-token
                  jsonPointers:
                    - /data
                - kind: StatefulSet
                  name: openebs-etcd
                  jsonPointers:
                    - /spec/template/metadata/annotations/checksum~1token-secret
            - name: traefik
              namespace: traefik-system
              project: core

            - name: cnpg
              namespace: cnpg-system
              project: system
              tier: system-operator
            - name: redis-operator
              namespace: redis-system
              project: system
              tier: system-operator
            - name: volsync
              namespace: volsync-system
              project: system
              tier: system-operator
            - name: kyverno
              namespace: kyverno
              project: system
              tier: system-operator

            - name: descheduler
              namespace: kube-system
              project: system
            - name: external-dns
              namespace: external-dns
              project: system
            - name: reloader
              namespace: kube-system
              project: system
            - name: cloudflare-tunnel
              namespace: tunnel-system
              project: system
            - name: crowdsec
              namespace: crowdsec-system
              project: system

            # Monitoring
            - name: prometheus
              namespace: monitoring
              project: monitoring
            - name: grafana
              namespace: monitoring
              project: monitoring
            - name: prometheus-pve-exporter
              namespace: monitoring
              project: monitoring

            # Applications
            - name: oauth
              namespace: application
              project: application
              tier: system
            - name: adguardhome
              namespace: application
              project: application
              tier: system

            - name: kaneo
              namespace: application
              project: application
            - name: karakeep
              namespace: application
              project: application
            - name: n8n
              namespace: application
              project: application
            - name: termix
              namespace: application
              project: application
            - name: filebrowser
              namespace: application
              project: application
            - name: syncthing
              namespace: application
              project: application
            - name: affine
              namespace: application
              project: application
            - name: jellyfin
              namespace: application
              project: application
            - name: cloudbeaver
              namespace: application
              project: application
            - name: metube
              namespace: application
              project: application
            - name: miniflux
              namespace: application
              project: application
            - name: calibre
              namespace: application
              project: application
            - name: whoami
              namespace: application
              project: application
            - name: atuin
              namespace: application
              project: application
            - name: gitea
              namespace: application
              project: application
            - name: webhook-tester
              namespace: application
              project: application
            - name: glance
              namespace: application
              project: application
            - name: woodpecker
              namespace: woodpecker
              project: application

    strategy:
      type: AllAtOnce
      rollingSync:
        steps:
          - matchExpressions:
              - key: tier
                operator: In
                values: [core]
            maxUpdate: 1 # can be 0
          - matchExpressions:
              - key: tier
                operator: In
                values: [system-operator]
            maxUpdate: 1 # can be 0
          - matchExpressions:
              - key: tier
                operator: In
                values: [argocd]
            maxUpdate: 1 # can be 0
          - matchExpressions:
              - key: tier
                operator: In
                values: [system]
            maxUpdate: 1 # can be 0
          - matchExpressions:
              - key: tier
                operator: In
                values: [monitoring]
            maxUpdate: 1 # can be 0
          - matchExpressions:
              - key: tier
                operator: In
                values: [application]
            maxUpdate: 1 # can be 0

    template:
      metadata:
        name: "{{.name}}"
        finalizers: []
        labels:
          tier: "{{.tier | default .project}}"
      spec:
        project: "{{.project}}"
        syncPolicy:
          # Proposal https://argo-cd.readthedocs.io/en/stable/proposals/sync-timeout/#proposal
          # terminate:
          #   timeout: 10m
          automated:
            selfHeal: true
            prune: true
          syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
            - ServerSideDiff=true
            - RespectIgnoreDifferences=true
            - ApplyOutOfSyncOnly=true
            - SkipDryRunOnMissingResource={{.skipCrdsCheck | default false}}
        source:
          repoURL: *repo
          targetRevision: *branch
          path: "kubernetes/charts/{{.path | default .name}}"
        destination:
          name: *cluster
          namespace: "{{.namespace}}"
    templatePatch: |
      {{- with .noServerSideDiff }}
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: ServerSideDiff=false
      {{- end }}

      spec:
        project: "{{.project}}"
        {{- with .ignoreDifferences }}
        ignoreDifferences:
          {{- range . }}
          -
            {{. | toYaml | nindent 6}}
          {{- end }}
        {{- end }}

projects:
  system:
    namespace: argocd
    description: System Components
    finalizers: []
    sourceRepos:
      - *repo
    destinations:
      - name: *cluster
        namespace: kube-system
      - name: *cluster
        namespace: external-dns
      - name: *cluster
        namespace: redis-system
      - name: *cluster
        namespace: cnpg-system
      - name: *cluster
        namespace: volsync-system
      - name: *cluster
        namespace: kyverno
      - name: *cluster
        namespace: tunnel-system
      - name: *cluster
        namespace: crowdsec-system
    clusterResourceWhitelist: &clusterResourceWhitelist
      - group: "*"
        kind: "*"
    namespaceResourceWhitelist: &namespaceResourceWhitelist
      - group: "*"
        kind: "*"
    syncWindows: &syncWindows
      - kind: allow
        schedule: "0 3-7 * * *"
        timeZone: "Asia/Bangkok"
        applications:
          - "*"
        duration: 1h
        manualSync: false
      - kind: deny
        schedule: "0 0-3,8-23 * * *"
        timeZone: "Asia/Bangkok"
        applications:
          - "*"
        duration: 1h
        manualSync: true

  core:
    namespace: argocd
    description: Core Components
    finalizers: []
    sourceRepos:
      - *repo
    destinations:
      - name: *cluster
        namespace: kube-system
      - name: *cluster
        namespace: cilium-secrets
      - name: *cluster
        namespace: csi-addons-system
      - name: *cluster
        namespace: openebs
      - name: *cluster
        namespace: external-secrets
      - name: *cluster
        namespace: cert-manager
      - name: *cluster
        namespace: traefik-system
    clusterResourceWhitelist: *clusterResourceWhitelist
    namespaceResourceWhitelist: *namespaceResourceWhitelist
    syncWindows: *syncWindows

  monitoring:
    namespace: argocd
    description: Monitoring
    finalizers: []
    sourceRepos:
      - *repo
    destinations:
      - name: *cluster
        namespace: monitoring
    clusterResourceWhitelist: *clusterResourceWhitelist
    namespaceResourceWhitelist: *namespaceResourceWhitelist
    syncWindows: *syncWindows

  cicd: &cicd
    namespace: argocd
    description: CICD
    finalizers: []
    sourceRepos:
      - *repo
    destinations:
      - name: *cluster
        namespace: argocd
    clusterResourceWhitelist: *clusterResourceWhitelist
    namespaceResourceWhitelist: *namespaceResourceWhitelist
    syncWindows: *syncWindows

  argocd: *cicd

  application:
    namespace: argocd
    description: Applications
    finalizers: []
    sourceRepos:
      - *repo
    destinations:
      - name: *cluster
        namespace: application
      - name: *cluster
        namespace: woodpecker
    clusterResourceWhitelist: *clusterResourceWhitelist
    namespaceResourceWhitelist: *namespaceResourceWhitelist
    syncWindows:
      - kind: deny
        schedule: "0 * * * *"
        timeZone: "Asia/Bangkok"
        applications:
          - "*"
        duration: 1h
        manualSync: true
