---
# https://github.com/argoproj/argo-helm/blob/main/charts/argocd-apps/values.yaml

x-data:
  repo: &repo https://github.com/moonlight8978/lbh-lab.git
  branch: &branch main
  cluster: &cluster in-cluster

applicationsets:
  prod:
    namespace: argocd
    finalizers: []
    #   - resources-finalizer.argocd.argoproj.io
    goTemplate: true
    goTemplateOptions: ["missingkey=default"]
    generators:
      - list:
          elements:
            - name: argocd-apps
              namespace: argocd
              project: cicd
            - name: argocd
              namespace: argocd
              project: cicd

            - name: cilium
              namespace: kube-system
              project: system
            - name: coredns
              namespace: kube-system
              project: system
            - name: external-secrets
              namespace: external-secrets
              project: system
            - name: descheduler
              namespace: kube-system
              project: system
            - name: cert-manager
              namespace: cert-manager
              project: system
            - name: addons
              namespace: kube-system
              project: system
            - name: openebs
              namespace: openebs
              project: system
    template:
      metadata:
        name: "{{.name}}"
        finalizers: []
      spec:
        project: "{{.project}}"
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
          syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
            - ServerSideDiff=true
            - RespectIgnoreDifferences=true
            - ApplyOutOfSyncOnly=true
        source:
          repoURL: *repo
          targetRevision: *branch
          path: "kubernetes/charts/{{.path | default .name}}"
        destination:
          name: *cluster
          namespace: "{{.namespace}}"
    templatePatch: |
      {{- with .noServerSideDiff }}
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: ServerSideDiff=false
      {{- end }}

      spec:
        project: "{{.project}}"
        {{- with .ignoreDifferences }}
        ignoreDifferences:
          {{- range . }}
          -
            {{. | toYaml | nindent 6}}
          {{- end }}
        {{- end }}

projects:
  system:
    namespace: argocd
    description: System Components
    finalizers: []
    sourceRepos:
      - *repo
    destinations:
      - name: *cluster
        namespace: kube-system
      - name: *cluster
        namespace: cilium-secrets
      - name: *cluster
        namespace: external-secrets
      - name: *cluster
        namespace: cert-manager
      - name: *cluster
        namespace: openebs
    clusterResourceWhitelist: &clusterResourceWhitelist
      - group: "*"
        kind: "*"
    namespaceResourceWhitelist: &namespaceResourceWhitelist
      - group: "*"
        kind: "*"
    syncWindows: &syncWindows
      - kind: allow
        schedule: "0 3-7 * * *"
        timeZone: "Asia/Bangkok"
        applications:
          - "*"
        duration: 1h
        manualSync: false
      - kind: deny
        schedule: "0 0-3,8-23 * * *"
        timeZone: "Asia/Bangkok"
        applications:
          - "*"
        duration: 1h
        manualSync: true

  cicd:
    namespace: argocd
    description: CICD
    finalizers: []
    sourceRepos:
      - *repo
    destinations:
      - name: *cluster
        namespace: argocd
    clusterResourceWhitelist: *clusterResourceWhitelist
    namespaceResourceWhitelist: *namespaceResourceWhitelist
    syncWindows: *syncWindows
