# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json

scheme: https
hostname: &hostname syncthing-10-242-20-170.lab-local.bichls.dev
tz: &tz Asia/Bangkok

controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
    type: statefulset
    pod:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
    containers:
      main:
        image:
          repository: ghcr.io/syncthing/syncthing
          tag: 2.0.9
          pullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: &http 8384
          - containerPort: 22000
            protocol: UDP
          - containerPort: &sync 22000
            protocol: TCP
          - containerPort: 21027
            protocol: UDP
        envFrom:
          - configMap: main
        probes:
          liveness:
            path: /rest/noauth/health
            port: *http
          readiness:
            path: /rest/noauth/health
            port: *http
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 1Gi

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: openebs-mayastor
    accessMode: ReadWriteOnce
    size: 500Mi
  rootfs:
    type: persistentVolumeClaim
    storageClass: openebs-mayastor
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /var/syncthing

configMaps:
  main:
    includeInChecksum: true
    data:
      TZ: *tz
      STHOMEDIR: /config

service:
  main:
    controller: main
    ports:
      http:
        port: *http
        targetPort: *http
  sync:
    controller: main
    type: LoadBalancer
    annotations:
      lbipam.cilium.io/ips: 10.242.20.182
    ports:
      sync:
        port: *sync
        targetPort: *sync

route:
  main:
    parentRefs:
      - name: envoy
        namespace: envoy-gateway-system
    hostnames:
      - *hostname
    rules:
      - backendRefs:
          - identifier: main
            port: *http
            weight: 1
