---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/core/namespace-v1.json

kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce: privileged
  annotations:
    argocd.argoproj.io/hook: PreSync
