---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: rook-ceph-cluster
    namespace: rook-ceph
    repo: oci://ghcr.io/rook/
    name: rook-ceph-cluster
    version: v1.18.1
    valuesFile: cluster/values.yaml

  - releaseName: rook-ceph
    namespace: rook-ceph
    repo: oci://ghcr.io/rook/
    name: rook-ceph
    version: v1.18.2
    valuesFile: operator/values.yaml
