machine:
  kubelet:
    extraMounts:
      - destination: /var/local/openebs
        type: bind
        source: /var/local/openebs
        options:
          - rbind
          - rshared
          - rw
  nodeLabels:
    openebs.io/csi-node: mayastor
    openebs.io/engine: mayastor
