---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json

defaultPodOptions:
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true
  annotations:
    reloader.stakater.com/auto: "true"

controllers:
  main:
    containers:
      main:
        image:
          repository: casbin/casdoor
          tag: v2.100.0
          pullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: &http 8000
        probes:
          liveness:
            path: /healthz
            port: *http
          readiness:
            path: /healthz
            port: *http
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 256Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        envFrom:
          - configMap: main

configMaps:
  main:
    includeInChecksum: true
    data:
      RUNNING_IN_DOCKER: "true"

persistence:
  conf:
    type: configMap
    name: casdoor-config
  data:
    type: persistentVolumeClaim
    storageClass: openebs-mayastor
    accessMode: ReadWriteOnce
    size: 500Mi
  logs:
    type: persistentVolumeClaim
    storageClass: openebs-mayastor-single
    accessMode: ReadWriteOnce
    size: 500Mi
  tmp:
    type: emptyDir
    sizeLimit: 200Mi

service:
  main:
    controller: main
    ports:
      http:
        port: *http
        targetPort: *http

route:
  external:
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
    hostnames:
      - id.bichls.dev
    parentRefs:
      - name: traefik-external
        namespace: traefik-system
        sectionName: https
    rules:
      - backendRefs:
          - identifier: main
            port: *http
  internal:
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
    hostnames:
      - casdoor-10-242-20-170.lab-local.bichls.dev
    parentRefs:
      - name: traefik-internal
        namespace: traefik-system
        sectionName: https
    rules:
      - backendRefs:
          - identifier: main
            port: *http
