---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cilium/cilium/refs/heads/main/install/kubernetes/cilium/values.schema.json

kubeProxyReplacement: true
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445

autoDirectNodeRoutes: true
routingMode: native
ipv4NativeRoutingCIDR: "10.42.0.0/16"
ipam:
  mode: kubernetes
ipv6:
  enabled: false
loadBalancer:
  mode: dsr
  dsrDispatch: opt
  algorithm: maglev

l2announcements:
  enabled: true

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

hubble:
  enabled: false
  metrics:
    enabled:
      - dns:query
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium
  relay:
    enabled: false
    rollOutPods: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
    prometheus:
      serviceMonitor:
        enabled: true
  ui:
    enabled: false
    rollOutPods: true
    backend:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
    frontend:
      server:
        ipv6:
          enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 64Mi

envoy:
  enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

operator:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
