---
crds:
  enabled: true
  keep: true

enableCertificateOwnerRef: true

dns01RecursiveNameserversOnly: true
dns01RecursiveNameservers: 8.8.8.8:53,1.1.1.1:53

resources:
  requests:
    cpu: 50m
    memory: 64Mi

prometheus:
  enabled: true
  servicemonitor:
    enabled: true
