---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/external-secrets.io/externalsecret-v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kaneo-postgresql-creds
  namespace: application
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/basic-auth
  refreshPolicy: Periodic
  refreshInterval: 1h
  data:
    - secretKey: username
      remoteRef:
        key: kaneo/postgresql/username
    - secretKey: password
      remoteRef:
        key: kaneo/postgresql/password
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/external-secrets.io/externalsecret-v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kaneo-env
  namespace: application
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  refreshPolicy: Periodic
  refreshInterval: 1h
  data:
    - secretKey: JWT_ACCESS
      remoteRef:
        key: kaneo/api/JWT_ACCESS
    - secretKey: DATABASE_URL
      remoteRef:
        key: kaneo/api/DATABASE_URL
