---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/traefik.io/middleware-v1alpha1.json

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: casdoor
  namespace: application
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  chain:
    middlewares:
      - name: crowdsec
        namespace: traefik-system
