---
# yaml-language-server: $schema=https://raw.githubusercontent.com/moonlight8978/lbh-lab/refs/heads/jsonschema/external-secrets.io/externalsecret-v1.json

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: code-server-env
  namespace: application
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: code-server/app
