---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: external-dns-cloudflare
    namespace: external-dns
    repo: oci://ghcr.io/home-operations/charts-mirror/
    name: external-dns
    version: 1.19.0
    includeCRDs: true
    valuesFile: values.yaml

resources:
  - manifests/externalsecret.yaml
  - manifests/dnsendpoint.yaml
