# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json

hostname: &hostname termix-10-242-20-170.lab-local.bichls.dev
scheme: https
port: &port 8080

controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
    type: statefulset
    containers:
      main:
        image:
          repository: ghcr.io/lukegus/termix
          tag: release-1.6.0
          pullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: *port
        envFrom:
          - configMap: main
        probes:
          readiness:
            path: /health
            port: *port
          liveness:
            path: /health
            port: *port
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            memory: 512Mi

configMaps:
  main:
    data:
      PORT: "{{.Values.port}}"

persistence:
  main:
    type: persistentVolumeClaim
    storageClass: openebs-mayastor
    accessMode: ReadWriteOnce
    size: 1Gi
    advancedMounts:
      main:
        main:
          - path: /app/data
            readOnly: false

service:
  main:
    controller: main
    ports:
      http:
        port: *port
        targetPort: *port

route:
  main:
    parentRefs:
      - name: envoy
        namespace: envoy-gateway-system
    hostnames:
      - *hostname
    rules:
      - backendRefs:
          - identifier: main
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /
