---
# https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/values.yaml

fullnameOverride: zitadel

zitadel:
  configmapConfig:
    ExternalDomain: zitadel-10-242-20-170.lab-local.bichls.dev
    ExternalSecure: true
    ExternalPort: 443
    Database:
      Postgres:
        Host: zitadel-postgresql-rw
        Database: zitadel_production
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          Username: zitadel
          SSL:
            Mode: disable
  masterkeySecretName: zitadel-env

initJob:
  enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

extraManifests:
  - apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: zitadel
      namespace: application
      annotations:
        argocd.argoproj.io/sync-options: Replace=true
    spec:
      parentRefs:
        - name: traefik-internal
          namespace: traefik-system
          sectionName: https
      hostnames:
        - zitadel-10-242-20-170.lab-local.bichls.dev
      rules:
        - backendRefs:
            - name: zitaldel
              port: 8080
  - apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: zitadel-login
      namespace: application
      annotations:
        argocd.argoproj.io/sync-options: Replace=true
    spec:
      parentRefs:
        - name: traefik-internal
          namespace: traefik-system
          sectionName: https
      hostnames:
        - zitadel-login-10-242-20-170.lab-local.bichls.dev
      rules:
        - backendRefs:
            - name: zitaldel-login
              port: 3000
