---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: woodpecker
    namespace: woodpecker
    repo: oci://ghcr.io/woodpecker-ci/helm
    name: woodpecker
    version: 3.4.1
    valuesFile: values.yaml

resources:
  - manifests/externalsecret.yaml
