---
crds:
  enabled: true

monitoring:
  enabled: true

csi:
  enableRbdDriver: true
  enableCephfsDriver: true
  enableLiveness: true
  serviceMonitor:
    enabled: true

resources:
  limits:
    cpu: "1"
    memory: 512Mi
  requests:
    cpu: "200m"
    memory: 128Mi
