when:
  - event: push
    branch: main

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 0
      partial: false

steps:
  - name: Gitleaks
    image: ghcr.io/gitleaks/gitleaks:v8.29.1
    commands:
      - ls "$(pwd)"
      - gitleaks git --report-path=gitleaks-report.json --report-format=json --verbose --no-banner --exit-code 0
  - name: Extract leaks summary
    image: mikefarah/yq:4.49.2
    commands:
      - SECRETS_FOUND=$(yq -r '. | length' -p=json gitleaks-report.json)
      - echo "Found $SECRETS_FOUND secrets" > gitleaks-summary.txt
  - name: Notify leaks info
    image: ghcr.io/moonlight8978/shoutrrr-alpine:1.0.0
    commands:
      - shoutrrr send --url=$$NOTIFICATION_URL --title="lbh-lab secret scanning" --message="$(cat gitleaks-summary.txt)"
    environment:
      NOTIFICATION_URL:
        from_secret: notification-url
