# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cilium
    namespace: kube-system
    repo: https://helm.cilium.io/
    releaseName: cilium
    version: 1.17.5
    valuesFile: values.yaml
