---
kubeProxyReplacement: true
k8sServiceHost: 10.242.20.142
k8sServicePort: 6443

autoDirectNodeRoutes: true
routingMode: native
ipv4NativeRoutingCIDR: "10.42.0.0/16"
ipam:
  mode: kubernetes
ipv6:
  enabled: false
loadBalancer:
  mode: dsr
  dsrDispatch: opt
  algorithm: maglev

hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
  relay:
    enabled: true
    rollOutPods: true
    prometheus:
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
    rollOutPods: true

envoy:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
