kubeProxyReplacement: true
k8sServiceHost: 10.242.20.142
k8sServicePort: 6443

autoDirectNodeRoutes: true
routingMode: native
ipv4NativeRoutingCIDR: "10.42.0.0/16"
enableIPv4Masquerade: true
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList: "10.42.0.0/16"
ipv4:
  enabled: true
ipv6:
  enabled: false
loadBalancer:
  mode: dsr
  dsrDispatch: opt
  algorithm: maglev

hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    serviceMonitor:
      enabled: false
    dashboards:
      enabled: true
  relay:
    enabled: true
    rollOutPods: true
    prometheus:
      serviceMonitor:
        enabled: false
  ui:
    enabled: true
    rollOutPods: true

envoy:
  enabled: true
  prometheus:
    enabled: false
    serviceMonitor:
      enabled: true

operator:
  prometheus:
    enabled: false
    serviceMonitor:
      enabled: false

prometheus:
  enabled: false
  serviceMonitor:
    enabled: false
    trustCRDsExist: true
