kubeProxyReplacement: true
k8sServiceHost: 10.242.20.142
k8sServicePort: 6443

routingMode: native
loadBalancer:
  mode: dsr
  dsrDispatch: opt

hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
  relay:
    enabled: true
    rollOutPods: true
    prometheus:
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
    rollOutPods: true

operator:
  tolerations: []
