---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - namespace: argocd
    releaseName: argocd
    name: argocd
    repo: oci://ghcr.io/home-operations/charts-mirror/
    version: 8.1.3
    valuesFile: values.yaml
